---
language: python
python: "3.6"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install -r requirements.txt

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
