---
- name: Install glibc
  include_role:
    name: andrewrothstein.alpine-glibc-shim
- name: Install required packages
  apk:
    name: tar
- name: Create the Java directory
  file:
    path: /opt/java
    state: directory
- name: Download the Oracle JDK 1.8.0_191 tar.gz file
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-i586.tar.gz
    headers:
      Cookie: oraclelicense=accept-securebackup-cookie
    dest: /tmp
- name: Unarchive the Oracle JDK 1.8.0_191 tar.gz file
  unarchive:
    src: /tmp/jdk-8u191-linux-i586.tar.gz
    dest: /opt/java
    remote_src: yes
    owner: root
    group: root
- name: Set the Oracle JDK 1.8.0_191 as the current Java
  file:
    src: /opt/java/jdk1.8.0_191
    dest: /opt/java/current
    state: link
- name: Enable Java binaries
  file:
    src: "/opt/java/current/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
  loop:
    - java
    - javac