- name: Create instances "{{ instances }}"
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    service_account_email: sa1-294@iconic-monitor-297012.iam.gserviceaccount.com 
    credentials_file: /tmp/sa1-294.json
    project_id: iconic-monitor-297012
    machine_type: n1-standard-1
    image: centos-7
  tasks:
    - name: Launch instances "{{ instances }}"
      gce:
          instance_names: "{{ instances }}"
          machine_type: "{{ machine_type }}"
          image: "{{ image }}"
          service_account_email: "{{ service_account_email }}"
          credentials_file: "{{ credentials_file }}"
          project_id: "{{ project_id }}"
          disk_auto_delete: true
          preemptible: true
          tags: ansible
      register: gce
    - name: Wait for SSH to come up "{{ instances }}"
      wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
      with_items: "{{ gce.instance_data }}"
    - name: Add host to groupname "{{ instances }}"
      add_host: hostname={{ item.public_ip }} groupname=new_instances
      with_items: "{{ gce.instance_data }}"
    - name: Save host data "{{ instances }}"
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: gce_instances
      with_items: "{{ gce.instance_data }}"
